version: '3.7'

services:
  nginx:
    container_name: 'nginx'
    image: nginx:1.17-alpine
    ports:
      - 80:80
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - web_root:/var/www/html
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
    networks:
      - registry-frontend
      - registry-backend
    depends_on:
      - registry
  registry:
    container_name: 'registry'
    image: registry:2
    expose:
      - "5000"
    volumes:
      - registry_data:/var/lib/registry/
      - "./.auth/:/auth/"
    healthcheck:
      test: ["CMD", "wget", "-s", "localhost:5000/v2/"]
      interval: 5s
      timeout: 10s
    networks:
      - registry-backend
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
  registry-ui:
    container_name: 'ui'
    image: quiq/docker-registry-ui:latest
    expose:
      - "8000"
    volumes:
      - ui_data:/opt/data
      - "./configs/ui/config.yml:/opt/config.yml:ro"
    depends_on:
      - registry
    networks:
      - registry-backend
  certbot:
    image: certbot/certbot
    container_name: 'certbot'
    volumes:
      - web_root:/var/www/html
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email lparra.dev@gmail.com --agree-tos --no-eff-email -d registry.sector7g.rocks

networks:
  registry-backend:
  registry-frontend:

volumes:
  registry_data: {}
  ui_data: {}
  certbot_etc: {}
  certbot_var: {}
  web_root:
    driver: local
    driver_opts:
      type: none
      device: "/home/leonime/repos/docker-registry-test/www/html"
      o: bind