version: '3.7'

services:
  nginx:
    container_name: 'nginx'
    image: nginx:1.17-alpine
    ports:
      - 80:80
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - registry-frontend
      - registry-backend
    depends_on:
      - registry
  registry:
    container_name: 'registry'
    image: registry:2
    expose:
      - "5000"
    volumes:
      - registry_data:/var/lib/registry/
      - "./.auth/:/auth/"
    healthcheck:
      test: ["CMD", "wget", "-s", "localhost:5000/v2/"]
      interval: 5s
      timeout: 10s
    networks:
      - registry-backend
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm

networks:
  registry-backend:
  registry-frontend:

volumes:
  registry_data: {}